name: "scraping"

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year"
        required: true
        type: number

jobs:
  scraping:
    name: scraping
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set year
        id: set-year
        run: echo "YEAR=${{ github.event.inputs.year }}" >> $GITHUB_ENV

      - name: run
        run: uv run src/main.py --year ${{ env.YEAR }}

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: data/${{ env.YEAR }}.json

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scraping

    permissions:
      id-token: write
      pages: write

    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
